try:
    print(name)
except NameError as e:
    print('出现了变量为定义的异常')